#!/usr/bin/env python3
import os
import sys
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

# 8x10 pixel grid bitmap definitions for standard ASCII characters
PIXEL_MAP = {
    "A": [
        "  ████  ",
        " ██  ██ ",
        " ██  ██ ",
        " ██████ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        "        ",
    ],
    "B": [
        " █████  ",
        " ██  ██ ",
        " ██  ██ ",
        " █████  ",
        " ██  ██ ",
        " ██  ██ ",
        " █████  ",
        "        ",
    ],
    "C": [
        "  █████ ",
        " ██  ██ ",
        " ██     ",
        " ██     ",
        " ██     ",
        " ██  ██ ",
        "  █████ ",
        "        ",
    ],
    "D": [
        " █████  ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " █████  ",
        "        ",
    ],
    "E": [
        " ██████ ",
        " ██     ",
        " ██     ",
        " █████  ",
        " ██     ",
        " ██     ",
        " ██████ ",
        "        ",
    ],
    "F": [
        " ██████ ",
        " ██     ",
        " ██     ",
        " █████  ",
        " ██     ",
        " ██     ",
        " ██     ",
        "        ",
    ],
    "G": [
        "  █████ ",
        " ██  ██ ",
        " ██     ",
        " ██ ███ ",
        " ██  ██ ",
        " ██  ██ ",
        "  █████ ",
        "        ",
    ],
    "H": [
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██████ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        "        ",
    ],
    "I": [
        " ██████ ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        " ██████ ",
        "        ",
    ],
    "J": [
        "  █████ ",
        "    ██  ",
        "    ██  ",
        "    ██  ",
        "    ██  ",
        " ██ ██  ",
        "  ███   ",
        "        ",
    ],
    "K": [
        " ██  ██ ",
        " ██ ██  ",
        " ████   ",
        " ███    ",
        " ████   ",
        " ██ ██  ",
        " ██  ██ ",
        "        ",
    ],
    "L": [
        " ██     ",
        " ██     ",
        " ██     ",
        " ██     ",
        " ██     ",
        " ██     ",
        " ██████ ",
        "        ",
    ],
    "M": [
        " ██  ██ ",
        " ██████ ",
        " ██████ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        "        ",
    ],
    "N": [
        " ██  ██ ",
        " ███ ██ ",
        " ██████ ",
        " ██████ ",
        " ██ ███ ",
        " ██  ██ ",
        " ██  ██ ",
        "        ",
    ],
    "O": [
        "  ████  ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "P": [
        " █████  ",
        " ██  ██ ",
        " ██  ██ ",
        " █████  ",
        " ██     ",
        " ██     ",
        " ██     ",
        "        ",
    ],
    "Q": [
        "  ████  ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██ ██  ",
        " ██  ██ ",
        "  █████ ",
        "        ",
    ],
    "R": [
        " █████  ",
        " ██  ██ ",
        " ██  ██ ",
        " █████  ",
        " ████   ",
        " ██ ██  ",
        " ██  ██ ",
        "        ",
    ],
    "S": [
        "  █████ ",
        " ██  ██ ",
        " ██     ",
        "  ████  ",
        "     ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "T": [
        " ██████ ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "        ",
    ],
    "U": [
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "V": [
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        "   ██   ",
        "        ",
    ],
    "W": [
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██  ██ ",
        " ██████ ",
        " ██████ ",
        " ██  ██ ",
        "        ",
    ],
    "X": [
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        "   ██   ",
        "  ████  ",
        " ██  ██ ",
        " ██  ██ ",
        "        ",
    ],
    "Y": [
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "        ",
    ],
    "Z": [
        " ██████ ",
        "     ██ ",
        "    ██  ",
        "   ██   ",
        "  ██    ",
        " ██     ",
        " ██████ ",
        "        ",
    ],
    "0": [
        "  ████  ",
        " ██  ██ ",
        " ██ █ ██",
        " ██ █ ██",
        " ██ █ ██",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "1": [
        "   ██   ",
        "  ███   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        " ██████ ",
        "        ",
    ],
    "2": [
        "  ████  ",
        " ██  ██ ",
        "     ██ ",
        "   ███  ",
        "  ██    ",
        " ██     ",
        " ██████ ",
        "        ",
    ],
    "3": [
        "  ████  ",
        " ██  ██ ",
        "     ██ ",
        "   ███  ",
        "     ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "4": [
        "   ███  ",
        "  ████  ",
        " ██ ██  ",
        " ██ ██  ",
        " ██████ ",
        "    ██  ",
        "    ██  ",
        "        ",
    ],
    "5": [
        " ██████ ",
        " ██     ",
        " █████  ",
        "     ██ ",
        "     ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "6": [
        "  ████  ",
        " ██  ██ ",
        " ██     ",
        " █████  ",
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "7": [
        " ██████ ",
        "     ██ ",
        "    ██  ",
        "   ██   ",
        "  ██    ",
        "  ██    ",
        "  ██    ",
        "        ",
    ],
    "8": [
        "  ████  ",
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        " ██  ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    "9": [
        "  ████  ",
        " ██  ██ ",
        " ██  ██ ",
        "  █████ ",
        "     ██ ",
        " ██  ██ ",
        "  ████  ",
        "        ",
    ],
    " ": [
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ],
    ".": [
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "   ██   ",
        "   ██   ",
        "        ",
    ],
    ",": [
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "   ██   ",
        "   ██   ",
        "  ██    ",
    ],
    ":": [
        "        ",
        "   ██   ",
        "   ██   ",
        "        ",
        "   ██   ",
        "   ██   ",
        "        ",
        "        ",
    ],
    ";": [
        "        ",
        "   ██   ",
        "   ██   ",
        "        ",
        "   ██   ",
        "   ██   ",
        "  ██    ",
        "        ",
    ],
    "=": [
        "        ",
        "        ",
        " ██████ ",
        "        ",
        " ██████ ",
        "        ",
        "        ",
        "        ",
    ],
    "+": [
        "        ",
        "   ██   ",
        "   ██   ",
        " ██████ ",
        "   ██   ",
        "   ██   ",
        "        ",
        "        ",
    ],
    "-": [
        "        ",
        "        ",
        "        ",
        " ██████ ",
        "        ",
        "        ",
        "        ",
        "        ",
    ],
    "*": [
        "        ",
        " ██  ██ ",
        "  ████  ",
        " ██████ ",
        "  ████  ",
        " ██  ██ ",
        "        ",
        "        ",
    ],
    "/": [
        "      ██",
        "     ██ ",
        "    ██  ",
        "   ██   ",
        "  ██    ",
        " ██     ",
        "██      ",
        "        ",
    ],
    "\\": [
        "██      ",
        " ██     ",
        "  ██    ",
        "   ██   ",
        "    ██  ",
        "     ██ ",
        "      ██",
        "        ",
    ],
    "(": [
        "   ██   ",
        "  ██    ",
        " ██     ",
        " ██     ",
        " ██     ",
        "  ██    ",
        "   ██   ",
        "        ",
    ],
    ")": [
        "   ██   ",
        "    ██  ",
        "     ██ ",
        "     ██ ",
        "     ██ ",
        "    ██  ",
        "   ██   ",
        "        ",
    ],
    "[": [
        "  ████  ",
        "  ██    ",
        "  ██    ",
        "  ██    ",
        "  ██    ",
        "  ██    ",
        "  ████  ",
        "        ",
    ],
    "]": [
        "  ████  ",
        "    ██  ",
        "    ██  ",
        "    ██  ",
        "    ██  ",
        "    ██  ",
        "  ████  ",
        "        ",
    ],
    "{": [
        "   ███  ",
        "  ██    ",
        "  ██    ",
        " ██     ",
        "  ██    ",
        "  ██    ",
        "   ███  ",
        "        ",
    ],
    "}": [
        "  ███   ",
        "    ██  ",
        "    ██  ",
        "     ██ ",
        "    ██  ",
        "    ██  ",
        "  ███   ",
        "        ",
    ],
    "<": [
        "    ██  ",
        "   ██   ",
        "  ██    ",
        " ██     ",
        "  ██    ",
        "   ██   ",
        "    ██  ",
        "        ",
    ],
    ">": [
        "  ██    ",
        "   ██   ",
        "    ██  ",
        "     ██ ",
        "    ██  ",
        "   ██   ",
        "  ██    ",
        "        ",
    ],
    "_": [
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        " ██████ ",
        "        ",
    ],
    "!": [
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "        ",
        "   ██   ",
        "   ██   ",
        "        ",
    ],
    "?": [
        "  ████  ",
        " ██  ██ ",
        "     ██ ",
        "   ██   ",
        "   ██   ",
        "        ",
        "   ██   ",
        "        ",
    ],
    "#": [
        "  ██ ██ ",
        "  ██ ██ ",
        " ███████",
        "  ██ ██ ",
        " ███████",
        "  ██ ██ ",
        "  ██ ██ ",
        "        ",
    ],
    "$": [
        "   ██   ",
        "  █████ ",
        " ██ ██  ",
        "  ████  ",
        "  ██ ██ ",
        " █████  ",
        "   ██   ",
        "        ",
    ],
    "%": [
        " ██  ██ ",
        " ██  ██ ",
        "    ██  ",
        "   ██   ",
        "  ██    ",
        " ██  ██ ",
        " ██  ██ ",
        "        ",
    ],
    "&": [
        "  ██    ",
        " ██ ██  ",
        "  ██    ",
        " ██ ██  ",
        " ██  ██ ",
        " ██ ███ ",
        "  ███ ██",
        "        ",
    ],
    "'": [
        "   ██   ",
        "   ██   ",
        "  ██    ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ],
    '"': [
        "  ██ ██ ",
        "  ██ ██ ",
        "  ██ ██ ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ],
    "`": [
        "  ██    ",
        "   ██   ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ],
    "~": [
        "  ██ ██ ",
        " ██ ██  ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ],
    "@": [
        "  ████  ",
        " ██  ██ ",
        " ██ ███ ",
        " ██ █ ██",
        " ██ ███ ",
        " ██     ",
        "  ████  ",
        "        ",
    ],
    "^": [
        "   ██   ",
        "  ████  ",
        " ██  ██ ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
    ],
    "|": [
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "   ██   ",
        "        ",
    ],
}

# Auto-copy lowercase from uppercase if missing
for ch in range(ord("a"), ord("z") + 1):
    c = chr(ch)
    if c not in PIXEL_MAP:
        PIXEL_MAP[c] = PIXEL_MAP[c.upper()]


def build_pixel_font(font_name="MyCustomPixelFont", output_path="MyCustomPixelFont.ttf"):
    units_per_em = 1000
    grid_cols = 8
    grid_rows = 8
    pixel_size = units_per_em // grid_rows  # 125 units per pixel
    advance_width = grid_cols * pixel_size   # 1000 units (monospaced)
    baseline_offset = 125                     # Baseline shift

    # Map character to glyph name
    name_map = {
        " ": "space",
        ".": "period",
        ",": "comma",
        ":": "colon",
        ";": "semicolon",
        "=": "equal",
        "+": "plus",
        "-": "hyphen",
        "*": "asterisk",
        "/": "slash",
        "\\": "backslash",
        "(": "parenleft",
        ")": "parenright",
        "[": "bracketleft",
        "]": "bracketright",
        "{": "braceleft",
        "}": "braceright",
        "<": "less",
        ">": "greater",
        "_": "underscore",
        "!": "exclam",
        "?": "question",
        "#": "numbersign",
        "$": "dollar",
        "%": "percent",
        "&": "ampersand",
        "'": "quotesingle",
        '"': "quotedbl",
        "`": "grave",
        "~": "asciitilde",
        "@": "at",
        "^": "asciicircum",
def build_pixel_font(font_name="MyCustomPixelFont", output_path="MyCustomPixelFont.ttf", pixel_map_override=None):
    active_map = pixel_map_override if pixel_map_override else PIXEL_MAP
    units_per_em = 1000
    grid_cols = 8
    grid_rows = 8
    pixel_size = units_per_em // grid_rows  # 125 units per pixel
    advance_width = grid_cols * pixel_size   # 1000 units (monospaced)
    baseline_offset = 125                     # Baseline shift

    name_map = {
        " ": "space",
        ".": "period",
        ",": "comma",
        ":": "colon",
        ";": "semicolon",
        "=": "equal",
        "+": "plus",
        "-": "hyphen",
        "*": "asterisk",
        "/": "slash",
        "\\": "backslash",
        "(": "parenleft",
        ")": "parenright",
        "[": "bracketleft",
        "]": "bracketright",
        "{": "braceleft",
        "}": "braceright",
        "<": "less",
        ">": "greater",
        "_": "underscore",
        "!": "exclam",
        "?": "question",
        "#": "numbersign",
        "$": "dollar",
        "%": "percent",
        "&": "ampersand",
        "'": "quotesingle",
        '"': "quotedbl",
        "`": "grave",
        "~": "asciitilde",
        "@": "at",
        "^": "asciicircum",
        "|": "bar",
    }

    glyph_order = [".notdef", ".null", "nonmarkingreturn"]
    cmap = {}
    glyphs = {}

    pen = TTGlyphPen(None)
    glyphs[".notdef"] = pen.glyph()
    glyphs[".null"] = pen.glyph()
    glyphs["nonmarkingreturn"] = pen.glyph()

    for char, grid in active_map.items():
        gname = name_map.get(char, char)
        glyph_order.append(gname)
        cmap[ord(char)] = gname

        pen = TTGlyphPen(None)
        for row_idx, row_str in enumerate(grid):
            y_top = (grid_rows - row_idx) * pixel_size - baseline_offset
            y_bottom = y_top - pixel_size
            for col_idx, col_char in enumerate(row_str):
                if col_char != " ":
                    x_left = col_idx * pixel_size
                    x_right = x_left + pixel_size
                    pen.moveTo((x_left, y_bottom))
                    pen.lineTo((x_right, y_bottom))
                    pen.lineTo((x_right, y_top))
                    pen.lineTo((x_left, y_top))
                    pen.closePath()

        glyphs[gname] = pen.glyph()

    metrics = {name: (advance_width, 0) for name in glyph_order}

    fb = FontBuilder(units_per_em, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=875, descent=-125)
    fb.setupOS2(sTypoAscender=875, sTypoDescender=-125, usWinAscent=875, usWinDescent=125)
    fb.setupNameTable({
        "familyName": font_name,
        "styleName": "Regular",
        "uniqueFontIdentifier": f"DataStuff:{font_name}:2026",
        "fullName": font_name,
        "version": "Version 1.000",
        "psName": font_name.replace(" ", ""),
    })
    fb.setupPost()
    fb.save(output_path)
    print(f"Successfully generated font: {output_path}")

if __name__ == "__main__":
    import json
    font_name = sys.argv[1] if len(sys.argv) > 1 else "AntigravityPixel"
    out_file = sys.argv[2] if len(sys.argv) > 2 else f"{font_name}.ttf"
    json_path = sys.argv[3] if len(sys.argv) > 3 else None

    pixel_override = None
    if json_path and os.path.exists(json_path):
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            if "fontName" in data and data["fontName"]:
                font_name = data["fontName"]
            if "pixelMap" in data:
                pixel_override = data["pixelMap"]

    build_pixel_font(font_name, out_file, pixel_map_override=pixel_override)
